// src/lib/constants.ts

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua e Barbuda",
  "Arabia Saudita",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaigian",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Belgio",
  "Belize",
  "Benin",
  "Bhutan",
  "Bielorussia",
  "Birmania",
  "Bolivia",
  "Bosnia ed Erzegovina",
  "Botswana",
  "Brasile",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambogia",
  "Camerun",
  "Canada",
  "Capo Verde",
  "Ciad",
  "Cile",
  "Cina",
  "Cipro",
  "Città del Vaticano",
  "Colombia",
  "Comore",
  "Corea del Nord",
  "Corea del Sud",
  "Costa d'Avorio",
  "Costa Rica",
  "Croazia",
  "Cuba",
  "Danimarca",
  "Dominica",
  "Ecuador",
  "Egitto",
  "El Salvador",
  "Emirati Arabi Uniti",
  "Eritrea",
  "Estonia",
  "Etiopia",
  "Figi",
  "Filippine",
  "Finlandia",
  "Francia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germania",
  "Ghana",
  "Giamaica",
  "Giappone",
  "Gibuti",
  "Giordania",
  "Grecia",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guinea Equatoriale",
  "Guyana",
  "Haiti",
  "Honduras",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Irlanda",
  "Islanda",
  "Isole Marshall",
  "Isole Salomone",
  "Israele",
  "Italia",
  "Kazakistan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettonia",
  "Libano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Lussemburgo",
  "Macedonia del Nord",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldive",
  "Mali",
  "Malta",
  "Marocco",
  "Mauritania",
  "Mauritius",
  "Messico",
  "Micronesia",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Mozambico",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvegia",
  "Nuova Zelanda",
  "Oman",
  "Paesi Bassi",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nuova Guinea",
  "Paraguay",
  "Perù",
  "Polonia",
  "Portogallo",
  "Qatar",
  "Regno Unito",
  "Repubblica Ceca",
  "Repubblica Centrafricana",
  "Repubblica del Congo",
  "Repubblica Democratica del Congo",
  "Repubblica Dominicana",
  "Romania",
  "Rwanda",
  "Russia",
  "Saint Kitts e Nevis",
  "Saint Vincent e Grenadine",
  "Samoa",
  "San Marino",
  "Santa Lucia",
  "São Tomé e Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Slovacchia",
  "Slovenia",
  "Somalia",
  "Spagna",
  "Sri Lanka",
  "Stati Uniti",
  "Sudafrica",
  "Sudan",
  "Sudan del Sud",
  "Suriname",
  "Svezia",
  "Svizzera",
  "Swaziland",
  "Tagikistan",
  "Taiwan",
  "Tanzania",
  "Thailandia",
  "Timor Est",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunisia",
  "Turchia",
  "Turkmenistan",
  "Tuvalu",
  "Ucraina",
  "Uganda",
  "Ungheria",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const COUNTRY_PREFIXES = [
  { code: "+39", flag: "🇮🇹", name: "Italia" },
  { code: "+1", flag: "🇺🇸", name: "USA" },
  { code: "+44", flag: "🇬🇧", name: "Regno Unito" },
  { code: "+33", flag: "🇫🇷", name: "Francia" },
  { code: "+49", flag: "🇩🇪", name: "Germania" },
  { code: "+34", flag: "🇪🇸", name: "Spagna" },
  { code: "+41", flag: "🇨🇭", name: "Svizzera" },
  { code: "+32", flag: "🇧🇪", name: "Belgio" },
  { code: "+31", flag: "🇳🇱", name: "Paesi Bassi" },
  { code: "+43", flag: "🇦🇹", name: "Austria" },
  { code: "+351", flag: "🇵🇹", name: "Portogallo" },
  { code: "+30", flag: "🇬🇷", name: "Grecia" },
  { code: "+46", flag: "🇸🇪", name: "Svezia" },
  { code: "+47", flag: "🇳🇴", name: "Norvegia" },
  { code: "+45", flag: "🇩🇰", name: "Danimarca" },
  { code: "+358", flag: "🇫🇮", name: "Finlandia" },
  { code: "+48", flag: "🇵🇱", name: "Polonia" },
  { code: "+420", flag: "🇨🇿", name: "Rep. Ceca" },
  { code: "+36", flag: "🇭🇺", name: "Ungheria" },
  { code: "+40", flag: "🇷🇴", name: "Romania" },
  { code: "+353", flag: "🇮🇪", name: "Irlanda" },
  { code: "+7", flag: "🇷🇺", name: "Russia" },
  { code: "+90", flag: "🇹🇷", name: "Turchia" },
  { code: "+380", flag: "🇺🇦", name: "Ucraina" },
  { code: "+86", flag: "🇨🇳", name: "Cina" },
  { code: "+81", flag: "🇯🇵", name: "Giappone" },
  { code: "+82", flag: "🇰🇷", name: "Corea del Sud" },
  { code: "+91", flag: "🇮🇳", name: "India" },
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "+55", flag: "🇧🇷", name: "Brasile" },
  { code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "+52", flag: "🇲🇽", name: "Messico" },
  { code: "+20", flag: "🇪🇬", name: "Egitto" },
  { code: "+27", flag: "🇿🇦", name: "Sudafrica" },
  { code: "+971", flag: "🇦🇪", name: "UAE" },
  { code: "+966", flag: "🇸🇦", name: "Arabia Saudita" },
  { code: "+972", flag: "🇮🇱", name: "Israele" },
  { code: "+376", flag: "🇦🇩", name: "Andorra" },
  { code: "+355", flag: "🇦🇱", name: "Albania" },
  { code: "+374", flag: "🇦🇲", name: "Armenia" },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria" },
  { code: "+385", flag: "🇭🇷", name: "Croazia" },
  { code: "+357", flag: "🇨🇾", name: "Cipro" },
  { code: "+372", flag: "🇪🇪", name: "Estonia" },
  { code: "+354", flag: "🇮🇸", name: "Islanda" },
  { code: "+371", flag: "🇱🇻", name: "Lettonia" },
  { code: "+370", flag: "🇱🇹", name: "Lituania" },
  { code: "+352", flag: "🇱🇺", name: "Lussemburgo" },
  { code: "+356", flag: "🇲🇹", name: "Malta" },
  { code: "+373", flag: "🇲🇩", name: "Moldavia" },
  { code: "+377", flag: "🇲🇨", name: "Monaco" },
  { code: "+382", flag: "🇲🇪", name: "Montenegro" },
  { code: "+389", flag: "🇲🇰", name: "Macedonia" },
  { code: "+378", flag: "🇸🇲", name: "San Marino" },
  { code: "+381", flag: "🇷🇸", name: "Serbia" },
  { code: "+421", flag: "🇸🇰", name: "Slovacchia" },
  { code: "+386", flag: "🇸🇮", name: "Slovenia" },
  { code: "+39", flag: "🇻🇦", name: "Vaticano" },
].sort((a, b) => a.name.localeCompare(b.name));
